# Generated by Django 5.1.1 on 2024-09-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Opções'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Questões'},
        ),
    ]
